### ISSUE TITLE
Cant connect vagrant server with SSH

### ISSUE THREAD

**Issue by ragecub3** [eugene-manuilov/phalcon-vm#20]
I didnt see any username or password anywhere. How can i connect with ssh and use phalcon commands ?

**Comment by eugene-manuilov** [comment]
Just go to the phalcon-vm folder and run `vagrant ssh`. It should bring you into the vagrant instance without  entering a password

**Comment by ragecub3** [comment]
Thank you so much. I logged in to vagrant when i try to use phalcon commands i get an error "This command should be invoked inside a Phalcon project directory"
But im in my project directory in vagrant ssh
Directory  : vagrant/www/projectname/htdocs

**Comment by eugene-manuilov** [comment]
Looks like you need to create an empty `.phalcon` folder. Run in the same folder following command:

```
mkdir .phalcon
```

After doing it you should be able to run phalcon devtool command. Let me know if it helps you.

**Comment by ragecub3** [comment]
Yep ! It works. Thank you so much.

**Comment by eugene-manuilov** [comment]
Have fun! ;)
